import { ShieldAlert, BadgeCheck, Leaf, Wrench, ClipboardList, Users, Truck } from "lucide-react";
import type { ChampionKey } from "@/data/zeus";

export const CHAMPION_ICONS: Record<ChampionKey, any> = {
  seguridad: ShieldAlert,
  calidad: BadgeCheck,
  ambiental: Leaf,
  mantenimiento: Wrench,
  gestion: ClipboardList,
  gente: Users,
  logistica: Truck,
};

export const PRE_REQUISITES_LIST = ["WVD", "ACADIA", "CORREO", "MANGYVER", "SAP", "CORE", "IAL", "ETO", "SPLAN", "SUITE 360"];

export const STRINGS = {
  SEARCH_PLACEHOLDER: "Buscar por operador, equipo o líder…",
  NO_TEAM: "Sin Equipo",
  NO_EQUIPMENT: "Sin equipos",
  NOT_ASSIGNED: "No asignado",
  DRIVERS_LICENSE: "Driver's License",
  INTERMEDIATE: "Intermediate",
  ADVANCED: "Advanced",
  SAFETY_TERRITORY: "Territorio Safety",
  AUTONOMY_LEVEL: "PROMEDIO HABILIDADES",
  ATO: "ATO",
  MANAGE_IPS_TITLE: "Gestionar IPs",
  SELECT_IPS_SUBTITLE: "Seleccionar IPs para el operador",
  GLOBAL_LIST_SUBTITLE: "Administrar Lista Global (Para todos)",
  ADD_BUTTON: "AÑADIR",
  REMOVE_BUTTON: "ELIMINAR",
  EXPIRED_ASSESSMENT: "+2 Meses",
  LEADER_LABEL: "Líder:",
  TEAM_LOGO_OFFICIAL: "Logo Oficial del Equipo",
  LOGO_FALLBACK: "LOGO",
  TEAM_SUGGESTIONS: "Sugerencias de tu equipo",
};

export const BANCO_IPS_COCIMIENTOS = [
  "pH mosto frío",
  "EMO mosto frío",
  "RDF mosto frío",
  "%HLD",
  "Color mosto frío",
  "Amargor mosto frío",
  "Tiempo de disolución",
  "Tiempo de filtración",
  "Minutos de atraso en arranque de cocedor",
  "Tiempo de calentamiento de ollas",
  "% Merma de Silos",
  "Velocidad de Aspiración",
  "% de vaciado de filtro",
  "Merma de Cribado y Molienda",
  "Eficiencia de Filtración",
  "Tiempo total de filtración (min)",
  "Volumen Total de Cocimiento",
  "Desguaces de silos al vaciar",
  "Resultado de inventario cíclico",
  "Consumo a órdenes en un periodo de 24 horas",
  "Cumplimiento de programa de cambio de fase en factores de autonomía",
  "Temperatura de arranque de Macerador",
  "Temperatura de agua de riego",
  "pH TACAS",
  "% de evaporación",
  "Consumo de vapor (kg/hl mosto)",
  "Tiempo de residencia en rotapool (tiempo de traslado)",
  "Tiempo de enfriamiento de mosto",
  "IBU mosto frío",
  "Color mosto",
  "Tiempo de exposición por atorones de cartón",
  "Fugas de polvo en Bodega",
  "Cero impactos (FMS)",
  "Exposición por fallas en equipos",
  "Cumplimiento de reporte de ACIS",
  "Cumplimiento de rampa"
];
