const fs = require('fs');

const rawData = `32044789 JUAN ISIDRO CAMPOS | Técnico Eléctrico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32045043 LUIS ANTONIO RAMIREZ | Técnico Instrumentista 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32045106 ARTURO VELAZQUEZ | Técnico Eléctrico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32045952 VICTOR MENDOZA | Técnico Instrumentista 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32146005 RAMON COLLAZO | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32219806 PABLO CESAR OROZCO | Técnico Instrumentista 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32044478 SERGIO ENRIQUE RODRIGUEZ | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32045116 JOSE LEANDRO MARTINEZ | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32045139 RICARDO ESPARZA | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32143106 VICTOR HUGO ZAPATA | Operador de BBT 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32173446 JOSE EDUARDO ALVARADO | Operador de Fermentación 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32044314 JOSE MARIA LUJAN | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32197835 MARIO ALBERTO REYES | Operador de Molienda 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32102191 MARIO ALBERTO ZAMARRIPA | Operador de Maceración 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32092747 JOSE GABRIEL RODRIGUEZ | Técnico Instrumentista 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32044251 GERARDO ESPARZA | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32044909 HERIBERTO LIMON | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32043804 ALEJANDRO LOPEZ | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32238801 SHERLYN GARCIA | Operador de BBT 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32239674 OSCAR RODRIGUEZ | Operador de Fermentación 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32218817 MARCO AURELIO CUAUCOATL RAMIREZ | Operador de Materias Primas 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32149237 HELMER DEL REAL | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32186666 SAMANTHA MONTSERRAT ROJERO | Operador de Molienda 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32233326 RAFAEL VERA | Operador de Molienda 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32044983 RAUL BAÑUELOS | Operador de Molienda 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32132054 RUBEN CARRILLO | Operador de Molienda 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32197833 JORGE LUIS RODRIGUEZ | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32209921 OSCAR EDUARDO VALDEZ | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32201712 JUAN CARLOS MORALES | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32236166 VICTOR HUGO ASCENCIO | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32213345 MANUEL DE JESUS FALCON | Operador de BBT 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32222224 RICARDO ESTEBAN JARAMILLO | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32199766 LUIS OTONIEL PACHECO | Técnico Eléctrico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32173447 ALEJANDRO DE JESUS ROBLES | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32044235 JESUS EDUARDO BRICEÑO | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32149607 JORGE ALBERTO ORTIZ | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32157221 JESUS MENCHACA | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32177303 ALDO ADRIAN SIFUENTES | Operador de Maceración 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32188809 ALDO ERNESTO SILVA | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32044502 ABEL GUILLERMO MAZATAN | Operador de Materias Primas 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32181152 BETSAIDA GUERRERO | Operador de Materias Primas 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32149490 JUAN ANTONIO RIVERA | Técnico Eléctrico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32044301 EDUARDO NERI | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32111307 FRANCISCO JAVIER VARELA | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32149238 OSWALDO DELGADILLO | Operador de Fermentación 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32044316 SERGIO TRUJILLO | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32146003 LUIS FERNANDO ZAPATA | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32144778 JUAN FRANCISCO GARCIA | Operador de Fermentación 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32043739 LAZARO QUEZADA | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32176714 JOSE EUSEBIO IBARRA | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32045149 ENRIQUE MEDINA | Operador de Fermentación 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32145333 FLAVIO CESAR DIAZ | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32044513 HUMBERTO RODARTE | Operador de Fermentación 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32043886 RAFAEL CHAVEZ | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32189922 JOSE GUADALUPE VALLE | Operador de Molienda 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32044319 MARCO ANTONIO MENCHACA | Técnico Mecánico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY
32132055 JOSE AMADOR RODRIGUEZ | Operador de Maceración 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32173445 JOSE LUIS CAZARES | Operador de Maceración 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32148922 JUAN ANTONIO VALDEZ | Operador de Maceración 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32227225 MANUEL DE JESUS DEL REAL ESQUIVEL | Operador de Maceración 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32044514 LUIS MANUEL DOMINGUEZ | Operador de Fermentación 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32223727 ARTURO RODARTE | Técnico Eléctrico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32144776 WILMAR YOEL GONZALEZ | Operador de Fermentación 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32230100 LUIS ARMANDO REYES | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32043902 ARTURO SAUCEDO | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32224127 CARLOS EDUARDO ENRIQUEZ | Operador de BBT 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32043835 FILIBERTO PINEDO | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32043900 VICTOR MANUEL HURTADO | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32045469 ANDRES SARABIA | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32173442 MARIO DAVID CASTAÑEDA | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32044776 BENITO VALLE | Operador de Fermentación 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32043861 VICTOR MANUEL DE JESUS SIMENTAL | Técnico Mecánico 2.0 | NAHUALES | LUIS MANUEL GARCIA VICTORIO
32043891 ARMANDO RAYZOLA | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32044751 JUAN MANUEL HUERTA | Operador de Fermentación 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32219854 JOSE LUIS MALDONADO | Operador de Molienda 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32045574 PEDRO PALOS | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32186837 JOSE MANUEL VARELA | Operador de Maceración 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32204284 ADRIAN HERNANDEZ | Operador de Materias Primas 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32045438 HUGO ALBERTO CARDONA | Operador de Materias Primas 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32132194 HECTOR HUGO VALDEZ | Operador de Maceración 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32154634 EDGAR RENE DIAZ | Operador de BBT 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32188533 GUILLERMO GERARDO GONZALEZ | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32181156 ALBADINNE MAGDALENA TORRES | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32201713 RODOLFO ESPARZA | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32044771 RAFAEL MARTINEZ | Operador de Fermentación 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32148846 RIGOBERTO MOTA | Operador de Maceración 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32044760 MAURICIO ARELLANO | Operador de Fermentación 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32233327 ISAI SOLORZANO | Operador de Fermentación 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32202933 OMAR ALBERTO ROBLES | Operador de Materias Primas 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32142953 GERMAN RUEDAS | Operador de Filtración de Cerveza 2.0 | BRAVOS DEL FRIO | RAUL DAVID CORTES ALANIZ
32044246 MIGUEL ANGEL SANCHEZ | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32043796 JUAN RAMON JIMENEZ | Operador de Materias Primas 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32044838 J MARIO TRUJILLO | Operador de Materias Primas 2.0 | LOS CAZADORES DEL AMARGOR | FÁTIMA NEDITH GOMEZ MIRELES
32046259 JOSE CARLOS CARDONA | Operador de Maceración 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32222277 CARLOS RIVERA | Operador de Filtración de Cerveza 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32231911 ANA PAOLA PERERA | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32045409 ALBERTO NUÑEZ | Operador de Materias Primas 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32045134 PEDRO MALDONADO | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32197427 EDGAR ZAMARRON | Operador de Maceración 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32045076 ERON GUARDADO | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32237827 CONCEPCION REYES | Operador de Materias Primas 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32044783 SANTIAGO HERRERA | Operador de Materias Primas 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32044037 MANUEL DE JESUS CHAVEZ | Operador de Materias Primas 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32044839 JAIME LOPEZ | Operador de Materias Primas 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32045572 J GUADALUPE GUZMAN | Operador de Materias Primas 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32179720 JOSE REFUGIO LOPEZ | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32045510 J MANUEL RAYGOZA | Operador de Maceración 2.0 | MASH-RAINBOW | RODRÍGUEZ RANGEL JOSÉ LUIS
32045396 JUAN GABRIEL HERNANDEZ | Operador de Filtración de Cerveza 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32197834 LUIS ADOLFO MALDONADO | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32238258 VALERIA NATALY CASTAÑON | Operador de Materias Primas 2.0 | CUCHILLAS | JUAN SALAZAR BANDA
32044892 LEOBARDO VARELA | Operador de Maceración 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32045128 JESUS CALDERON | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32181712 CARLOS ADRIAN ROBLES | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32209589 EDGAR EMMANUEL JUAREZ ALBA | Operador de Maceración 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32043849 PEDRO ANTONIO URIBE | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32237975 LUIS RICARDO VALDES | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32222222 EFREN GONZALEZ CONTRERAS | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32045410 RODOLFO CABRERA | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32213349 PEDRO LUIS RODRIGUEZ | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32045357 GUSTAVO MELENCIANO | Operador de Fermentación 2.0 | LOS BRONCOS | MIGUEL ANGEL RIVERA MUÑOZ
32222223 HECTOR MANUEL DE LA ROSA | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32175115 NESTOR MONTOYA | Operador de Filtración de Cerveza 2.0 | REYES DE LA MEZCLA | RODRIGO REGALADO PALOMEQUE
32144777 OSCAR CAMPOS | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32132025 SERGIO MIGUEL PARRA | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32045004 J JESUS RIVERA | Operador de Materias Primas 2.0 | MOSTO-BOYS | OBED CALVILLO RAMIREZ
32044036 VICTOR SOTO | Operador de Fermentación 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32149605 JUAN MANUEL RODARTE | Operador de Filtración de Cerveza 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO
32043880 JAIME CID | Operador de Fermentación 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32237862 CESAR RODRIGUEZ BANDA | Operador de BBT 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA
32131972 OSCAR IVAN IBARRA | Operador de Molienda 2.0 | LOS PANCHITOS | JOSÉ FRANCISCO TORRES LÓPEZ
32204174 ALEXIS BERLIN ALVAREZ CORONA | Operador de BBT 2.0 | LOS FUERTES DEL FRIO | IVAN ALEJANDRO ROJERO MALDONADO`;

const lines = rawData.trim().split('\n');

const operators = lines.map(line => {
    // Some lines are separated by pipe to easily distinguish, but wait, the first ones are:
    // "32044789 JUAN ISIDRO CAMPOS | Técnico Eléctrico 2.0 | MUNICH | JUAN CARLOS CALVILLO GARAY"
    // The rest I just formatted like:
    // "32045116 JOSE LEANDRO MARTINEZ | Operador de Filtración de Cerveza 2.0 | ANDAMOS CON TODO | JUAN JOSE MEJIA MONTOYA"
    
    let parts = line.split('|').map(p => p.trim());
    if (parts.length < 4) {
        console.error("Invalid line format:", line);
        return null;
    }

    const firstPart = parts[0];
    const id = firstPart.split(' ')[0];
    const nombre = firstPart.substring(id.length).trim();
    
    const puesto = parts[1];
    const equipoAutonomo = parts[2];
    const lider = parts[3];
    
    let area = "desconocido";
    const lowerPuesto = puesto.toLowerCase();
    if (lowerPuesto.includes("técnico")) area = "mantenimiento";
    else if (lowerPuesto.includes("maceración") || lowerPuesto.includes("molienda") || lowerPuesto.includes("materias primas")) area = "cocimientos";
    else if (lowerPuesto.includes("filtración") || lowerPuesto.includes("fermentación") || lowerPuesto.includes("bbt")) area = "bloque frio";

    return {
        id,
        nombre,
        puesto,
        area,
        equipoAutonomo,
        lider,
        roles: []
    };
}).filter(Boolean);

fs.writeFileSync('../public/operators.json', JSON.stringify(operators, null, 2));
console.log('Wrote', operators.length, 'operators to public/operators.json');
